export const CANVAS_W = 600
export const CANVAS_H = 890
export const PADDLE_H = 20 //paleta
export const PADDLE_W = 170 //paleta
export const BALL_RAD = 35
export const BLOCK_RAD = 20
export const MAX_LEVEL = 2
export const LIVES = 3
export const BLOCK_W = 90   // ancho bloque
export const BLOCK_H = 53   // alto bloque
export const VELOCIDAD_X_NIVEL = 1
export const VELOCIDAD_BASE = 2