export const CANVAS_W = 600
export const CANVAS_H = 890
export const PADDLE_H = 20 //paleta
export const PADDLE_W = 180 //paleta
export const BALL_RAD = 30
export const BLOCK_RAD = 20
export const MAX_LEVEL = 3
export const LIVES = 3
export const BLOCK_W = 90   // ancho bloque
export const BLOCK_H = 53   // alto bloque